In [1]:
import numpy as np
from collections import Counter
import pandas as pd

In [34]:
with open("11/input.txt") as f:
    arr = []
    for line in f:
        l = [int(x) for x in line[:-1]]
        arr += [l]
nparr = np.array(arr)
s = 0
for _ in range(100):
    nparr = nparr + 1
    fl = np.zeros_like(nparr)
    n = 0
    n_ant = -1
    while n - n_ant > 0:
        for i in range(nparr.shape[0]):
            for j in range(nparr.shape[1]):
                if nparr[i][j] > 9 and fl[i][j] == 0:
                    fl[i][j] = 1
                    for ii in range(-1, 2):
                        for jj in range(-1, 2):
                            if i + ii in range(nparr.shape[0]) and j + jj in range(nparr.shape[1]):
                                nparr[i+ii][j+jj] += 1
        n_ant = n
        n = (fl == 1).sum()
    nparr[nparr > 9] = 0
    s += n
print(nparr)
print(s)

[[8 2 2 2 2 2 2 2 7 5]
 [2 2 2 2 2 2 2 2 3 7]
 [2 2 2 2 2 2 2 2 4 0]
 [2 2 2 2 2 2 2 2 5 0]
 [2 2 2 2 2 2 2 2 5 0]
 [2 2 2 2 2 2 2 2 5 0]
 [2 2 2 2 2 2 2 3 6 2]
 [2 2 2 2 2 2 3 5 1 1]
 [3 3 2 2 2 3 5 1 1 1]
 [1 3 2 2 2 3 1 1 1 9]]
1637


In [36]:
with open("11/input.txt") as f:
    arr = []
    for line in f:
        l = [int(x) for x in line[:-1]]
        arr += [l]
nparr = np.array(arr)
step = 0
while True:
    nparr = nparr + 1
    fl = np.zeros_like(nparr)
    n = 0
    n_ant = -1
    while n - n_ant > 0:
        for i in range(nparr.shape[0]):
            for j in range(nparr.shape[1]):
                if nparr[i][j] > 9 and fl[i][j] == 0:
                    fl[i][j] = 1
                    for ii in range(-1, 2):
                        for jj in range(-1, 2):
                            if i + ii in range(nparr.shape[0]) and j + jj in range(nparr.shape[1]):
                                nparr[i+ii][j+jj] += 1
        n_ant = n
        n = (fl == 1).sum()
    step += 1
    nparr[nparr > 9] = 0
    if n == nparr.shape[0] * nparr.shape[1]: break
    
print(nparr)
print(step)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
242
